version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '5432:${DB_PORT}'
    volumes:
      - db:/var/lib/postgresql/data
  api:
    container_name: inventory-api
    build:
      context: ./
      target: development
    image: inventory-api
    depends_on:
      - db
    ports:
      - ${PORT}:${PORT}
    environment:
      NODE_ENV: ${ENV}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    links:
      - db
    external_links:
      - db
    volumes:
      - './:/code'
    env_file:
      - .env
    command: yarn run dev
volumes:
  db:
    driver: local
